server:
  port: 8088


spring:
  profiles:
    active: dev
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      max-active: 255
      initial-size: 5
      max-wait: 20000
      min-idle: 5
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.whyalwaysmea.account.po
  configuration:
    map-underscore-to-camel-case: true

mapper:
    mappers:
        - com.whyalwaysmea.account.utils.MyMapper
    # insert和update中，是否判断字符串类型!=''
    not-empty: false
    identity: MYSQL

pagehelper:
    # 指定分页插件使用哪种方言
    helperDialect: mysql
    # 分页合理化参数,当该参数设置为 true 时，pageNum<=0 时会查询第一页， pageNum>pages（超过总数时），会查询最后一页
    reasonable: true
    # 通过Mapper 接口参数来传递分页参数：分页插件会从查询方法的参数值中，自动根据上面 params 配置的字段中取值
    supportMethodsArguments: true
    # 为了支持startPage(Object params)方法，增加了该参数来配置参数映射，用于从对象中根据属性名取值
    params: pageNum=page;pageSize=limit
